#!/usr/bin/env node
/**
 * Regenerate skills/kitbash/SKILL.md from the live rubric, so the standalone skill
 * (installed via `npx skills add`) can never drift from what the `kitbash` tool hands out.
 *
 *   npm run build && npm run skill
 *
 * Sections 1-6 of the rubric apply verbatim and are embedded as-is. Section 7 tells the
 * agent to call the kitbash_verify MCP tool, which a skill-only install does not have, so
 * it is replaced below with the `kitbash-mcp verify` CLI — the same pipeline, reached
 * through a shell.
 *
 * Everything around the rubric is presentation: the skill page on skills.sh renders this
 * file, so it opens with what the skill is and when to use it rather than with an
 * implementation note.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildRubric } from '../rubric.js';

const OUT = fileURLToPath(new URL('../../skills/kitbash/SKILL.md', import.meta.url));

/**
 * The commit the skill's verify command runs from.
 *
 * NOT a convenience. `npx github:owner/repo` with no ref runs whatever is on main at that
 * moment, and a security audit of this skill flagged exactly that: unpinned remote
 * execution of GitHub-hosted code. A pinned commit cannot change under the person running
 * it. Move this forward deliberately when the verifier changes, and regenerate.
 */
const PIN = 'ffa0f30d66823a0689fcfd9b90176f9cb7de4abd';

const rubric = buildRubric({
  idea: "<the user's idea, in their own words>",
  stack: '<the stack the user named — drop this constraint if they did not name one>',
  target_license: '<the SPDX id they ship under — drop this constraint if unstated>',
});

// Split on section 7's banner. If the rubric is ever restructured this throws, rather
// than silently shipping a skill that tells the agent to call a tool it does not have.
const parts = rubric.split(/\n=+\n7\. STOP/);
if (parts.length !== 2) throw new Error('rubric section 7 not found — update src/scripts/skill.ts');

const skill = `---
name: kitbash
description: Decide what to borrow, adapt, or write before building something. Use when the user describes an app, tool, CLI, or feature they want to build and needs to know which parts already exist as open-source GitHub repos (BORROW), which are worth reading and adapting (KITBASH), and which to just write (WRITE). Every repository named is checked against the live GitHub API, so invented ones never reach the user.
---

<!-- Generated by \`npm run skill\` from src/rubric.ts. Edit the rubric, not this file. -->

# Kitbash

Most of what someone is about to build already exists. This skill breaks an idea into
components, gives each one a verdict — **BORROW**, **KITBASH**, or **WRITE** — and checks
every repository it names against the live GitHub API, so the invented ones are gone
before the user sees the answer.

## When to Use This Skill

Use this skill when the user:

- Describes an app, tool, CLI, or feature they want to build
- Asks "is there a library for this" or "should I use a package or write it myself"
- Is about to hand-roll something in a domain where correctness was hard-won (PDF parsing, timezone math, OAuth, codecs, Unicode, crypto)
- Wants a build plan that names real, maintained dependencies instead of plausible-sounding ones
- Asks which parts of a project are worth writing themselves

## The Three Verdicts

| Verdict | Meaning |
| --- | --- |
| **BORROW** | A maintained library exists and the correctness was hard-won. Rewriting it is the mistake — take the dependency. |
| **KITBASH** | A good reference exists but is not a clean fit. Read it, adapt the approach, leave the dependency. |
| **WRITE** | Generic enough that you should just write it. No repository needed. |

## How It Works

1. Decompose the idea into 3-6 functionally distinct components.
2. Give every component exactly one verdict, and recall 1-3 candidate repositories for the BORROW and KITBASH ones.
3. Verify the whole slate — every repository is resolved against the GitHub API, and the ones that do not exist are dropped and counted.
4. Present the verified report, and only that.

If the \`kitbash\` and \`kitbash_verify\` MCP tools are connected, call \`kitbash\` instead:
same flow, with verification as a tool call rather than a shell command.

## The Rubric

Follow it exactly, then run the verification step below.

\`\`\`text
${parts[0]!.trimEnd()}
\`\`\`

## Verify Before You Answer

The slate is unverified recall, and some of the repositories in it do not exist. Verification
is what makes the answer trustworthy, so it runs before the user sees anything.

Pipe the whole slate, WRITE components included, into the verifier in one call (needs Node 18+):

\`\`\`bash
npx -y github:Open-Dev-Society/kitbash#${PIN} verify <<'EOF'
{
  "idea": "<the idea, verbatim>",
  "stack": "<omit if unstated>",
  "target_license": "<omit if unstated>",
  "components": [ <the full ComponentCandidate[] array> ]
}
EOF
\`\`\`

### What that command runs

- Kitbash's own verifier, from \`github.com/Open-Dev-Society/kitbash\`, **pinned to commit
  \`${PIN.slice(0, 7)}\`** — the code is fixed at a revision you can read, not whatever is on
  main today.
- Its only network requests are read-only \`GET /repos/{owner}/{name}\` calls to
  \`api.github.com\`. It writes nothing outside its own package directory.
- **A GitHub token is optional.** If \`GITHUB_TOKEN\`, \`GH_TOKEN\`, or \`gh auth token\` is
  present it is sent as an \`Authorization\` header to \`api.github.com\` and to nothing else,
  needs no scopes, and is never logged or written to disk. Without one GitHub allows 60
  checks an hour, which covers a normal slate.
- If you would rather execute nothing, check each candidate yourself with
  \`curl -s -o /dev/null -w '%{http_code}' https://api.github.com/repos/OWNER/NAME\` and treat
  404 as "does not exist". You lose ranking, health flags and the rendered report, but the
  anti-hallucination check still holds.

It resolves every repository against the GitHub API, drops the ones that do not exist, flags
archived, unlicensed and abandoned ones, ranks the survivors, and prints a markdown report
followed by a \`<kitbash_result_json>\` block. Read \`next_action\` in that JSON:

- \`DONE\`: show the user the markdown report as-is. Do not add repositories to it, re-rank
  it, or restate it from memory — every fact in it was checked and yours were not.
- \`RECALL_REPLACEMENTS\`: every candidate died for one or more components. Propose new
  repositories for exactly those components and run the verifier again with the full slate.

If the verifier cannot run (no Node, no network), say so plainly and present the slate as
unverified recall. Repositories that were never checked are the one failure this skill
exists to prevent.
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, skill, 'utf8');
console.error(`[skill] wrote ${OUT}`);
