#!/usr/bin/env node
/**
 * Regenerate skills/kitbash/SKILL.md from the live rubric, so the standalone skill
 * (installed via `npx skills add`) can never drift from what the `kitbash` tool hands out.
 *
 *   npm run build && npm run skill
 *
 * Sections 1-6 of the rubric apply verbatim. Section 7 tells the agent to call the
 * kitbash_verify MCP tool, which a skill-only install does not have, so it is replaced
 * with the `kitbash-mcp verify` CLI — the same pipeline, reached through a shell.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildRubric } from '../rubric.js';

const OUT = fileURLToPath(new URL('../../skills/kitbash/SKILL.md', import.meta.url));

const rubric = buildRubric({
  idea: "<the user's idea, in their own words>",
  stack: '<the stack the user named — drop this constraint if they did not name one>',
  target_license: '<the SPDX id they ship under — drop this constraint if unstated>',
});

// Split on section 7's banner. If the rubric is ever restructured this throws, rather
// than silently shipping a skill that tells the agent to call a tool it does not have.
const parts = rubric.split(/\n=+\n7\. STOP/);
if (parts.length !== 2) throw new Error('rubric section 7 not found — update src/scripts/skill.ts');

const skill = `---
name: kitbash
description: Decide what to borrow, adapt, or write before building something. Use when the user describes an app, tool, or feature they want to build and needs to know which parts already exist as open-source GitHub repos (BORROW), which are worth reading and adapting (KITBASH), and which to just write (WRITE). Every repo named is checked against the live GitHub API before the user sees it.
---

<!-- Generated by \`npm run skill\` from src/rubric.ts. Edit the rubric, not this file. -->

# kitbash

If the \`kitbash\` and \`kitbash_verify\` MCP tools are connected, call \`kitbash\` instead and
follow what it returns. Everything below is the same flow for when they are not.

Follow the rubric, then run the verification step at the end. It is not optional.

\`\`\`text
${parts[0]!.trimEnd()}
\`\`\`

## 7. Verify. Do not present any of this to the user yet.

Nothing above has been checked, and some of the repos you just named do not exist. Do not
summarize the slate, preview the verdicts, or paste the JSON.

Pipe the whole slate, WRITE components included, into the verifier in one call
(needs Node 18+; picks up a GitHub token from \`GITHUB_TOKEN\`, \`GH_TOKEN\`, or
\`gh auth token\`, otherwise runs at 60 checks an hour):

\`\`\`bash
npx -y github:Open-Dev-Society/kitbash verify <<'EOF'
{
  "idea": "<the idea, verbatim>",
  "stack": "<omit if unstated>",
  "target_license": "<omit if unstated>",
  "components": [ <the full ComponentCandidate[] array> ]
}
EOF
\`\`\`

It resolves every repo against the GitHub API, drops the ones that do not exist, flags
archived, unlicensed and abandoned ones, ranks the survivors, and prints a markdown report
followed by a \`<kitbash_result_json>\` block. Read \`next_action\` in that JSON:

- \`DONE\`: show the user the markdown report as-is. Do not add repos to it, re-rank it,
  or restate it from memory.
- \`RECALL_REPLACEMENTS\`: every candidate died for one or more components. Propose new
  repos for exactly those components and run the verifier again with the full slate.

If the verifier cannot run (no Node, no network), say so plainly and present nothing as
verified. An unchecked repo list is the one failure this skill exists to prevent.
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, skill, 'utf8');
console.error(`[skill] wrote ${OUT}`);
